#!/bin/bash

# All Nerd Fonts:
# yay -S otf-aurulent-nerd
# yay -S otf-codenewroman-nerd
# yay -S otf-comicshanns-nerd
# yay -S otf-commit-mono-nerd
# yay -S otf-droid-nerd
# yay -S otf-firamono-nerd
# yay -S otf-geist-mono-nerd
# yay -S otf-hasklig-nerd
# yay -S otf-hermit-nerd
# yay -S otf-monaspace-nerd
# yay -S otf-opendyslexic-nerd
# yay -S otf-overpass-nerd
# yay -S ttf-0xproto-nerd
# yay -S ttf-3270-nerd
# yay -S ttf-agave-nerd
# yay -S ttf-anonymouspro-nerd
# yay -S ttf-arimo-nerd
# yay -S ttf-bigblueterminal-nerd
# yay -S tts-bigstream-vera-mono-nerd
# yay -S tts-cascadia-code-nerd
# yay -S tts-cousine-nerd
# yay -S ttf-d2coding-nerd
# yay -S ttf-daddytime-mono-nerd
# yay -S ttf-dejavu-nerd
# yay -S ttf-envycoder-nerd
# yay -S ttf-fantasque-nerd
# yay -S ttf-firacode-nerd
# yay -S ttf-go-nerd
# yay -S ttf-hack-nerd
# yay -S ttf-heavydata-nerd
# yay -S ttf-iawriter-nerd
# yay -S ttf-ibmplex-mono-nerd
# yay -S ttf-inconsolata-go-nerd
# yay -S ttf-inconsolata-lgc-nerd
# yay -S tff-inconsolata-nerd
# yay -S ttf-intone-nerd
# yay -S ttf-iosevkaterm-nerd
# yay -S ttf-jetbrains-mono-nerd
# yay -S ttf-lekton-nerd
# yay -S ttf-liberation-mono-nerd
# yay -S ttf-lilex-nerd
# yay -S ttf-martian-mono-nerd
# yay -S ttf-meslo-nerd
# yay -S ttf-monofur-nerd
# yay -S ttf-monoid-nerd
# yay -S ttf-mononoki-nerd
# yay -S ttf-mplus-nerd
# yay -S ttf-nerd-fonts-symbols
# yay -S ttf-nerd-fonts-symbols-mono
# yay -S ttf-noto-nerd
# yay -S ttf-profont-nerd
# yay -S ttf-proggyclean-nerd
# yay -S ttf-roboto-mono-nerd
# yay -S ttf-sharetech-mono-nerd
# yay -S ttf-sourcecodepro-nerd
# yay -S ttf-space-mono-nerd
# yay -S ttf-terminus-nerd
# yay -S ttf-tinos-nerd
# yay -S ttf-ubuntu-mono-nerd
# yay -S ttf-ubuntu-nerd
# yay -S ttf-victor-mono-nerd

# AUR Programs:
yay -S discord
